#pragma once

enum voucher : int {
    OVERSTOCK,
    CLEARANCE_SALE,
    HONE,
    REROLL_SURPLUS,
    CRYSTAL_BALL,
    TELESCOPE,
    GRABBER,
    WASTEFUL,
    TAROT_MERCHANT,
    PLANET_MERCHANT,
    SEED,
    BLANK,
    MAGIC_TRICK,
    HIEROGLYPH,
    DIRECTORS_CUT,
    PAINT_BRUSH,
    OVERSTOCK_PLUS,
    LIQUIDATION,
    GLOW_UP,
    REROLL_GLUT,
    OMEN_GLOBE,
    OBSERVATORY,
    NACHO_TONG,
    RECYCLOMANCY,
    TAROT_TYCOON,
    PLANET_TYCOON,
    MONEY_TREE,
    ANTIMATTER,
    ILLUSION,
    PETROGLYPH,
    RETCON,
    PALETTE,
    VOUCHER_COUNT
};

const char* voucherName(voucher);